name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    uses: TheHiddenCargo/central-pipelines/.github/workflows/sonarcloud-analysis.yml@2b44d8bec39fd69ad67ace3b004811f8e12ddc86
    with:
      java-version: '21'
      branch-name: 'main'
      coverage-exclusions: 'arsw/tamaltolimense/bidservice/config/**/*,arsw/tamaltolimense/bidservice/controller/**/*,arsw/tamaltolimense/bidservice/exception/**/*,arsw/tamaltolimense/bidservice/BidServiceApplication.*'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}